### ISSUE TITLE
Loading unichars

### ISSUE THREAD

**Issue by mxpiotrowski** [ndw/xmlunicode#5]
`load-file` doesn't seem to use `load-path` and looks for unichars.el in my home directory.  I would suggest to replace it with `load`, which honors `load-path`, so that unichars.el is also found when installed via MELPA.

**Comment by ndw** [comment]
Apparently I thought that load-file would be relative to the file containing the load. Maybe that's not the case. I think the right solution might be to have unichars.el (perhaps renamed xmlunicode-chars.el) provide a feature that can be required from xmlunicode.el.

**Comment by mxpiotrowski** [comment]
This sounds like a good idea to me!

**Comment by ndw** [comment]
Ok. I've done that and rearranged a few things. Please let me know if this fixes the problem or introduces new problems.
